language: ruby
rvm:
  - 2.0.0
  - 2.1.4
  - 2.2.0

sudo: false
cache: bundler

before_install: gem update --remote bundler

install:
  - bundle install --retry=3

script:
  - ruby test/run_test.rb

notifications:
  slack:
    secure: RXH3ZQMKr+ILfOxF2bY5VGv3VTKwb0nsl/w0nIRz5ZCJAIh6YkYY9OjtteKnQOryiVDd8EyZP9P9fXu2fqmmSWDMlf0sn6ttyx5RrQWQtNCqoCue76KMEKMm3nQa71wUhpqIU611oifiMI0fQrV453yfqEmV1xj4SibXI21rl/FqigbUI/1zjoXGphs5K1Il2hY+gP5hzeX9/Uf+2fIZueabcCJuOqwcLN/I8s3czaWYBF1YF9JRkSRRTbRGQyKtMnr+eL98LhwvnQPbwzFaeORLvx+EAk0OM2M74zxXb1NVVKOLyVCYfjRxzs9kPXocxko3V6TueHsTvjknLI0bLleEM8fV/9Q8+/W3bZfapwCzMpeYyyBWg7dpGIpZdwbO6sng4/uFu9xKrKiR6myTPXoTUX4vzy7hLJm5OAtBRy13Ataezjp/5P3Jz2YXIcIyl6R+OvKnXnS4safHzaloGwacpy0+ox94IEtIOmxbUndPhnBBfT4ghOKss8kd53rDT3ssnWnI8uRkJalyFLQN6vyCPaEhZGjKUawJgrMVnS5GoAVE+mAK+7KU0XD9GDsdWDzzdcK4R698y/x1SkT4OAWt5E01Gnx6APNqbjrIYZk456sRcJQYUnJxss/VbWkWFihZtXz/UFZ/xqwQdOPZO86JJI3mTh+yJGIExYs/L3s=
